### ISSUE TITLE
Fix parsing errors for MRT data

### ISSUE THREAD

**Issue by alistairking** [CAIDA/libparsebgp#49]
This is a catch-all issue for various parsing problems that we are finding as we attempt to parse all the MRT data available from the RIS and RV projects.

@digizeph has some testing scripts that will trawl through the data in a semi-automated fashion and will update this issue with files that cause either crashes or errors.

**Comment by digizeph** [comment]
Failed command:
```
bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/ris/rrc06/updates/2002/01/07/ris.rrc06.updates.1010407860.gz
```
Error message:
```
WARN: No time window specified, defaulting to all available data
WARN: INVALID_MSG: Path attribute (type 18) has length 20529, but only 31 bytes remain. (parsebgp_bgp_update.c:613)
bgpreader: parsebgp_bgp_update.c:1118: parsebgp_bgp_update_decode: Assertion `slen == sizeof(msg->path_attrs.len) + msg->path_attrs.len' failed.
Aborted (core dumped)
```

`libbgpstream` version: 
https://github.com/CAIDA/libbgpstream/commit/2a272847f0412ade8ee2fc1e9e24624c8b00af8f

**Comment by digizeph** [comment]
Failed command:
```
bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/ris/rrc00/updates/2018/01/14/ris.rrc00.updates.1515920100.gz
```

Error message: (note that the return code is still zero)
```
bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/ris/rrc00/updates/2018/01/14/ris.rrc00.updates.1515920100.gz>/dev/null
WARN: No time window specified, defaulting to all available data
Unexpected EOF while reading compressed file -- file is probably incomplete
Unexpected EOF while reading compressed file -- file is probably incomplete
2019-04-18 16:52:49 28185: bgpstream_parsebgp_common.c:538: ERROR: Could not refill buffer
```

`libbgpstream` version: 
https://github.com/CAIDA/libbgpstream/commit/2a272847f0412ade8ee2fc1e9e24624c8b00af8f

**Comment by alistairking** [comment]
oh. this last is not a parsing bug. the problem is that the file is truncated. things are working as they should

**Comment by digizeph** [comment]
The `Unexpected EOF while reading...` message comes from wandio https://github.com/wanduow/wandio/blob/master/lib/ior-zlib.c#L105.
I suspect that there are other reasons the refill can fail, thus we cannot conclude that it must be the truncated file (https://github.com/CAIDA/libbgpstream/blob/master/lib/formats/bgpstream_parsebgp_common.c#L538)

**Comment by kenkeys** [comment]
> Failed command:
> 
> ```
> bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/ris/rrc06/updates/2002/01/07/ris.rrc06.updates.1010407860.gz
> ```
> 
> Error message:
> 
> ```
> WARN: No time window specified, defaulting to all available data
> WARN: INVALID_MSG: Path attribute (type 18) has length 20529, but only 31 bytes remain. (parsebgp_bgp_update.c:613)
> bgpreader: parsebgp_bgp_update.c:1118: parsebgp_bgp_update_decode: Assertion `slen == sizeof(msg->path_attrs.len) + msg->path_attrs.len' failed.
> Aborted (core dumped)
> ```
> 
> `libbgpstream` version:
> [CAIDA/libbgpstream@2a27284](https://github.com/CAIDA/libbgpstream/commit/2a272847f0412ade8ee2fc1e9e24624c8b00af8f)

Fixed in 
[705716d](https://github.com/CAIDA/libparsebgp/commit/705716d939545bb3f96583e9aa3c69c2331126e5)

**Comment by digizeph** [comment]
> > Failed command:
> > ```
> > bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/ris/rrc06/updates/2002/01/07/ris.rrc06.updates.1010407860.gz
> > ```
> > Error message:
> > ```
> > WARN: No time window specified, defaulting to all available data
> > WARN: INVALID_MSG: Path attribute (type 18) has length 20529, but only 31 bytes remain. (parsebgp_bgp_update.c:613)
> > bgpreader: parsebgp_bgp_update.c:1118: parsebgp_bgp_update_decode: Assertion `slen == sizeof(msg->path_attrs.len) + msg->path_attrs.len' failed.
> > Aborted (core dumped)
> > ```
> > `libbgpstream` version:
> > [CAIDA/libbgpstream@2a27284](https://github.com/CAIDA/libbgpstream/commit/2a272847f0412ade8ee2fc1e9e24624c8b00af8f)
> 
> Fixed in
> [705716d](https://github.com/CAIDA/libparsebgp/commit/705716d939545bb3f96583e9aa3c69c2331126e5)

The program no-long core-dumps anymore, but there still seem to be some parsing error from libparsebgp:
```
WARN: No time window specified, defaulting to all available data
WARN: INVALID_MSG: Path attribute (type 18) has length 20529, but only 3 bytes remain. (parsebgp_bgp_update.c:574)
2019-04-19 21:51:15 2876: bgpstream_parsebgp_common.c:602: ERROR: Failed to parse message from 'http://bgp-archive.caida.org/ris/rrc06/updates/2002/01/07/ris.rrc06.updates.1010407860.gz' (-2:Invalid Message)
```

libparsebgp version used: 705716d939545bb3f96583e9aa3c69c2331126e5

**Comment by kenkeys** [comment]
> > > Failed command:
> > > ```
> > > bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/ris/rrc06/updates/2002/01/07/ris.rrc06.updates.1010407860.gz
> > > ```
> > > Error message:
> > > ```
> > > WARN: No time window specified, defaulting to all available data
> > > WARN: INVALID_MSG: Path attribute (type 18) has length 20529, but only 31 bytes remain. (parsebgp_bgp_update.c:613)
> > > bgpreader: parsebgp_bgp_update.c:1118: parsebgp_bgp_update_decode: Assertion `slen == sizeof(msg->path_attrs.len) + msg->path_attrs.len' failed.
> > > Aborted (core dumped)
> > > ```
> > > `libbgpstream` version:
> > > [CAIDA/libbgpstream@2a27284](https://github.com/CAIDA/libbgpstream/commit/2a272847f0412ade8ee2fc1e9e24624c8b00af8f)
> > 
> > 
> > Fixed in
> > [705716d](https://github.com/CAIDA/libparsebgp/commit/705716d939545bb3f96583e9aa3c69c2331126e5)
> 
> The program no-long core-dumps anymore, but there still seem to be some parsing error from libparsebgp:
> 
> ```
> WARN: No time window specified, defaulting to all available data
> WARN: INVALID_MSG: Path attribute (type 18) has length 20529, but only 3 bytes remain. (parsebgp_bgp_update.c:574)
> 2019-04-19 21:51:15 2876: bgpstream_parsebgp_common.c:602: ERROR: Failed to parse message from 'http://bgp-archive.caida.org/ris/rrc06/updates/2002/01/07/ris.rrc06.updates.1010407860.gz' (-2:Invalid Message)
> ```
> 
> libparsebgp version used: [705716d](https://github.com/CAIDA/libparsebgp/commit/705716d939545bb3f96583e9aa3c69c2331126e5)

Yes, the input appears to be corrupt, so this is the expected response (and obviously dumping core was not)

**Comment by digizeph** [comment]
**Core dump**:
```
bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/ris/rrc06/updates/2002/01/18/ris.rrc06.updates.1011359220.gz
```
```
WARN: No time window specified, defaulting to all available data
Segmentation fault (core dumped)
```
libparsebgp version: 705716d

**Comment by digizeph** [comment]
**Assertion failure, core dump: `slen == msg->announced_nlris.len`**

```
bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/ris/rrc03/updates/2002/01/19/ris.rrc03.updates.1011444360.gz > /dev/null
```
```
WARN: No time window specified, defaulting to all available data
bgpreader: parsebgp_bgp_update.c:1138: parsebgp_bgp_update_decode: Assertion `slen == msg->announced_nlris.len' failed.
Aborted (core dumped)
```

libparsebgp version: 705716d

**Comment by digizeph** [comment]
**Core dump**
```
bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/ris/rrc06/updates/2002/02/03/ris.rrc06.updates.1012757040.gz
```

v2beta5 output (a7e12c4):
```
bgpreader: parsebgp_bgp.c:130: parsebgp_bgp_decode: Assertion `msg->len == nread' failed.
Aborted (core dumped)
```

current version output (705716d):
```
Segmentation fault (core dumped)
```

_Note: previous version core dump with `Aborted` message, current version output with `Segmentation fault` message._

**Comment by digizeph** [comment]
**Assertion `slen == sizeof(msg->path_attrs.len) + msg->path_attrs.len' failed**

```
bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/ris/rrc06/updates/2002/02/04/ris.rrc06.updates.1012785840.gz
```

```
WARN: No time window specified, defaulting to all available data
WARN: NOT_IMPLEMENTED: BGP UPDATE Path Attribute 226 is not yet implemented (parsebgp_bgp_update.c:554)
bgpreader: parsebgp_bgp_update.c:1118: parsebgp_bgp_update_decode: Assertion `slen == sizeof(msg->path_attrs.len) + msg->path_attrs.len' failed.
```

**Comment by digizeph** [comment]
**Assertion `slen == msg->withdrawn_nlris.len' failed.**

`bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/routeviews/route-views6/updates/2004/05/19/routeviews.route-views6.updates.1084987620.bz2 > /dev/null`

```
bgpreader: parsebgp_bgp_update.c:1124: parsebgp_bgp_update_decode: Assertion `slen == msg->withdrawn_nlris.len' failed.
Aborted (core dumped)
```

libparsebgp version: d9c2dd56c1db47522cea3630448321ce8a6e7f6f

**Comment by alistairking** [comment]
We've started doing some large-scale comparisons of bgpstream v1 (which is based on an old fork of libbgpdump) and v2 (which is based on libparsebgp). I'll update this issue with problems that are (apparently) caused by libparsebgp.

**Comment by alistairking** [comment]
fewer records in v2 than in v1:

v1 command:
```
bgpreader -d singlefile -o upd-file,http://bgp-archive.caida.org/routeviews/route-views2/updates/2001/12/31/routeviews.route-views2.updates.1009784460.bz2
```

v2 command:
```
bgpreader -d singlefile -o upd-file=http://bgp-archive.caida.org/routeviews/route-views2/updates/2001/12/31/routeviews.route-views2.updates.1009784460.bz2
```
When using v1 we see 36,573 elems (by counting lines).
When using v2, we see 35,565 elems, and a warning:
```
WARNING: Skipping truncated record 3913
```
