### ISSUE TITLE
RIB parsing error

### ISSUE THREAD

**Issue by digizeph** [CAIDA/libparsebgp#76]
```
bgpreader -d singlefile -o rib-file=https://www.isolario.it/Isolario_MRT_data/Alderaan/2019_12/rib.20191211.0800.bz2 1>/dev/null
WARN: No time window specified, defaulting to all available data
2019-12-11 08:03:49 51094: bgpstream_parsebgp_common.c:594: ERROR: Failed to parse message from 'https://www.isolario.it/Isolario_MRT_data/Alderaan/2019_12/rib.20191211.0800.bz2' (-2:Invalid Message)
```

- `libbgpstream` version: https://github.com/CAIDA/libbgpstream/commit/64daa6204d50578af795c4d1133e82c2c06b9a3a. 
- `libparsebgp` version: https://github.com/CAIDA/libparsebgp/commit/ce34041d04c23ef2b548af1c298826aa08b5adb4

**Comment by digizeph** [comment]
Original issue: https://github.com/CAIDA/libbgpstream/issues/159

**Comment by x-bin** [comment]
> ```
> bgpreader -d singlefile -o rib-file=https://www.isolario.it/Isolario_MRT_data/Alderaan/2019_12/rib.20191211.0800.bz2 1>/dev/null
> WARN: No time window specified, defaulting to all available data
> 2019-12-11 08:03:49 51094: bgpstream_parsebgp_common.c:594: ERROR: Failed to parse message from 'https://www.isolario.it/Isolario_MRT_data/Alderaan/2019_12/rib.20191211.0800.bz2' (-2:Invalid Message)
> ```
> 
> * `libbgpstream` version: [CAIDA/libbgpstream@64daa62](https://github.com/CAIDA/libbgpstream/commit/64daa6204d50578af795c4d1133e82c2c06b9a3a).
> * `libparsebgp` version: [ce34041](https://github.com/CAIDA/libparsebgp/commit/ce34041d04c23ef2b548af1c298826aa08b5adb4)

Hi, I got the same issue when I parsing the isolario rib data, I just wondered whether the issue has been solved.

**Comment by digizeph** [comment]
I believe this issue is fixed @x-bin. I retried the same command above (I have to download the file to my machine first due to ssl certificate issue), and the bgpreader issue seems to work fine.

```
~/Downloads 
❯ bgpreader -d singlefile -o rib-file=rib.20191211.0800.bz2
WARN: No time window specified, defaulting to all available data
R|B|1576051200.000000|singlefile|singlefile|||V|1606142074
R|R|1576051200.000000|singlefile|singlefile|||24550|118.91.160.44|0.0.0.0/0|118.91.160.44|24550 58504|58504|||
R|R|1576051200.000000|singlefile|singlefile|||138195|103.86.45.237|0.0.0.0/0|103.86.45.237|138195 136800 64050|64050|17152:1||
R|R|1576051200.000000|singlefile|singlefile|||2593|95.140.133.13|0.0.0.0/0|95.140.133.13|2593 49289|49289|||
R|R|1576051200.000000|singlefile|singlefile|||11708|72.22.223.18|0.0.0.0/0|72.22.223.18|11708 32097|32097|||
R|R|1576051200.000000|singlefile|singlefile|||56911|185.169.236.14|0.0.0.0/0|185.169.236.14|56911|56911|||
R|R|1576051200.000000|singlefile|singlefile|||16004|217.29.66.1|0.0.0.0/0|217.29.66.1|16004 137|137|||
R|R|1576051200.000000|singlefile|singlefile|||35908|98.126.24.5|0.0.0.0/0|98.126.24.5|35908 3257|3257|||
R|R|1576051200.000000|singlefile|singlefile|||210025|192.187.100.218|0.0.0.0/0|192.187.100.218|210025 64515|64515|||
...
R|R|1576051200.000000|singlefile|singlefile|||56911|185.169.236.135|1.0.0.0/24|185.169.236.135|56911 13335|13335|13335:10052 13335:19020 13335:20050 13335:20500 13335:20530 56911:20002 56911:21305||
R|R|1576051200.000000|singlefile|singlefile|||56911|185.169.236.133|1.0.0.0/24|185.169.236.133|56911 13335|13335|13335:10039 13335:19020 13335:20050 13335:20500 13335:20530 56911:20002 56911:21103||
R|R|1576051200.000000|singlefile|singlefile|||24796|193.201.40.100|1.0.0.0/24|193.201.40.100|24796 39120 13335|13335|||
R|R|1576051200.000000|singlefile|singlefile|||12779|213.254.2.31|1.0.0.0/24|213.254.2.31|12779 13335|13335|12779:65049 12779:65097||
R|R|1576051200.000000|singlefile|singlefile|||198349|185.19.140.105|1.0.0.0/24|185.19.140.105|198349 1267 13335|13335|1267:180 1267:200||

~/Downloads 
❯ 
```
Could you confirm that you have the libbgpstream 2.0.0 installed instead of the previous release candidates? The full 2.0.0 comes with up-to-date libparsebgp which could include fixes not available on the version you have.
You can try reinstall the library: https://bgpstream.caida.org/docs/install/bgpstream#ubuntu

Bests,
Mingwei

**Comment by x-bin** [comment]
Hello, I have reinstalled the bgpstream, but it got the same issue when I use it to parse the isolario's MRT data in 2020.
`bgpreader -d singlefile -o rib-file=rib.20201101.0000 -m > temp
WARN: No time window specified, defaulting to all available data
2020-12-02 16:43:22 18962: bgpstream_parsebgp_common.c:601: ERROR: Failed to parse message from 'rib.20201101.0000' (-2:Invalid Message)`

**Comment by digizeph** [comment]
@x-bin could you provide a download link to the file you're having trouble parsing?

**Comment by digizeph** [comment]
@kenkeys could you take a look at the error occurred with the following command?
`bgpreader -d singlefile -o rib-file=https://www.isolario.it/Isolario_MRT_data/Alderaan/2019_12/rib.20191211.0800.bz2`
It prints out a bunch of records, but terminates very early with the error message 
`2020-12-02 05:39:45 1116054: bgpstream_parsebgp_common.c:599: ERROR: Failed to parse message from 'https://www.isolario.it/Isolario_MRT_data/Alderaan/2019_12/rib.20191211.0800.bz2' (-2:Invalid Message)`

**Comment by kenkeys** [comment]
The message that triggers the error has TABLE_DUMP_V2 subtype 8, which isn't implemented in libparsebgp.  It was defined by RFC 8050 in 2017 to allow a message to contain additional paths.  Implementing that will take some work.

**Comment by x-bin** [comment]
> @x-bin could you provide a download link to the file you're having trouble parsing?

Sure, the link is [https://isolario.it/Isolario_MRT_data/Alderaan/2020_11/rib.20201101.0000.bz2](url)

**Comment by digizeph** [comment]
> The message that triggers the error has TABLE_DUMP_V2 subtype 8, which isn't implemented in libparsebgp. It was defined by RFC 8050 in 2017 to allow a message to contain additional paths. Implementing that will take some work.

@kenkeys Do you think we could change the behaviour to throw unimplemented warning instead of error out instead?
