### ISSUE TITLE
CMake and C++ port

### ISSUE THREAD

**Issue by ozars** [CAIDA/libparsebgp#77]
I implemented CMake support and added extern C guards to headers for linking against some C++ code. I can submit a PR if you'd be interested in merging these changes.

https://github.com/ozars/libparsebgp-1/tree/cpp-compat

I'm creating a C++ wrapper around this library in a separate project (I preferred wrapping libparsebgp as it seems to provide more precise control compared to libbgpstream). I plan going with the name "libparsebgpxx", but I wouldn't want to cause any confusion due to naming especially in case you have any plans to offer C++ API. 

Is it okay if I go with that name?

Thanks!

**Comment by alistairking** [comment]
Hey!

Yeah, we'd happily take a PR for C++ support. I'm also fine to have CMake support, but I'm worried about maintaining support for it over time since we don't have much experience with it and don't use it. If you're willing to check in from time to time and keep it updated, then I'd be more than happy to have a PR for that too :)

We don't have any plans for C++ bindings, so it would be great if you wanted to put those together. I don't have too much of a preference about naming, but I'm not sure that the "xx" suffix is very explicit. How about libparsebgp-cpp?

Thanks for your interest in the project!

**Comment by ozars** [comment]
Great! Submitting PR. 

I tried to stick with layout of automake files for layout of cmake files as much as possible. I'd be happy to help maintaining cmake files as well. :)

libparsebgp-cpp sounds reasonable.

Thanks for creating and maintaining the project!

**Comment by alistairking** [comment]
After chatting a bit with @kenkeys, we're not convinced that adding cmake support is worth the likely future headaches trying to maintain two build systems.
Is there a reason that you cannot use the existing autoconf-based system?

Our current reasoning is that even if you're using cmake elsewhere, you should still be able to build and install this library using it's provided autoconf-based build scripts and then just link against it from within your cmake environment.
Is there something we're missing?

**Comment by ozars** [comment]
Cmake is relatively more popular among C++ projects and it makes it really simple to add a project as a subdirectory and git submodule (kinda like pkg-config + autconf subdir but with much saner interface imho). 

Cmake is nice to have, but I understand it can be burden from maintainers point of view and it's not absolutely necessary.

What do you guys think about extern guards? If they sound okay I can revert changes related to cmake.

**Comment by alistairking** [comment]
We're very happy to have the extern guards.
I'll let @kenkeys weigh in with what he thinks about that use case for cmake.

**Comment by kenkeys** [comment]
The extern guards are good.
I'm still not convinced that a small convenience for a small number of developers is worth the burden of maintaining a cmake build system in addition to the existing automake system.  OTOH, I think it probably would be a good idea to add a pkg-conf .pc file for those developers.

**Comment by ozars** [comment]
Yeah, I understand concerns related to maintenance. I reverted changes related to cmake.

I am planning to keep cmake files in parent directory of libparsebgp though, as it's likely to cause less friction for me for integration. My only concern would be dependencies on config.h generated by autotools. So, I hope dropping them wouldn't be an issue. AFAICS, the build was fine without them as AC_DEFINE already appends corresponding -D switches during compilation.
