### ISSUE TITLE
Assertion failure in `parsebgp_bgp_decode_ext`

### ISSUE THREAD

**Issue by alistairking** [CAIDA/libparsebgp#79]
Using the latest master version, and running:
```
curl http://bgp-archive.caida.org/routeviews/route-views.sg/updates/2019/02/17/routeviews.route-views.sg.updates.1550417400.bz2 | bzcat | ./tools/parsebgp mrt:-
```

I get:
```
Assertion failed: (msg->len == nread), function parsebgp_bgp_decode_ext, file parsebgp_bgp.c, line 137.
```

**Comment by alistairking** [comment]
It seems this might be some corrupted data, `msg->len` looks to be garbage:
```
 >> parsebgp_bgp_msg_t (56 bytes):
   Marker: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
   Length:        59392
   Type:              4
     KEEPALIVE

nread: 19
```

@kenkeys do you have any thoughts?

I'm wondering if we're at the point where the assert (https://github.com/CAIDA/libparsebgp/blob/master/lib/bgp/parsebgp_bgp.c#L137) is doing more harm than good and we should simply return an invalid message error.

**Comment by kenkeys** [comment]
Sounds good to me.
